MENU_ORDER = [
    "main_menu",
    "online_menu",
    "ranked_search_menu",
    "side_select",
    "character_select",
    "waiting_for_challenger",
    "new_challenger",
    "post_match",
    "no_rematch",
    "loading",
    "cancel_search",
]

MENU_DATA = {
    "main_menu": {
        "image": "main_menu.PNG",
        "commands": ["down", "b"],
    },
    "online_menu": {
        "image": "online_menu.PNG",
        "commands": ["b"],
    },
    "ranked_search_menu": {
        "image": "ranked_search_menu.PNG",
        "commands": ["up", "b"],
    },
    "side_select": {
        "image": "side_select.PNG",
        "commands": ["b"],
    },
    "character_select": {
        "image": "character_select.PNG",
        "commands": [],
    },
    "new_challenger": {
        "image": "new_challenger.PNG",
        "commands": ["b"],
    },
    "post_match": {
        "image": "post_match.PNG",
        "commands": ["b"],
    },
    "no_rematch": {"image": "no_rematch.PNG", "commands": ["b"]},
    "loading": {"image": "loading.PNG", "commands": []},
    "waiting_for_challenger": {
        "image": "waiting_for_challenger.PNG",
        "commands": [],
    },
    "cancel_search": {"image": "cancel_search.PNG", "commands": ["right", "b"]},
}

CHARACTERS = [
    [
        "kunimitsu",
        "ganryu",
        "zafina",
        "julia",
        "marduk",
        "anna",
        "geese",
        "eliza",
        "noctis",
        "lei",
        "aking",
        "negan",
        "leroy",
        "fahk",
    ],
    [
        "raven",
        "nina",
        "yoshimitsu",
        "dragunov",
        "hwoarang",
        "law",
        "shaheen",
        "akuma",
        "kazuya",
        "random",
        "heihachi",
        "kazumi",
        "chloe",
        "lili",
        "lars",
        "ling",
        "jack",
        "lee",
        "kuma",
    ],
    [
        "miguel",
        "bob",
        "bryan",
        "king",
        "steve",
        "paul",
        "josie",
        "katarina",
        "jin",
        "random",
        "dvj",
        "claudio",
        "gigas",
        "asuka",
        "alisa",
        "leo",
        "feng",
        "eddy",
        "panda",
    ],
]
